### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by masterzorag**
Hi Aldo, since I'm feeling the only one can build sprx on linux host, I'd like to share some info about...

### CODE REVIEW

**Comment by freddy38510** [comment]
Hi masterzorag, i'm really interesting to build sprx on linux. The only obstacle i found is that some files are missing in PS3 SDK for linux. The files in question are the binaries in "host-win32" folder for windows. For example: "ppu-lv2-gcc.exe"

Edit: Simply missing PS3 GCC Cell OS Lv2 Toolchain Sources.

**Review by aldostools — APPROVED** [review]

**Comment by masterzorag** [comment]
@freddy38510 exactly
but you know, I can't give you some kind of copyrighted material...
probably the zipped file is laying somewhere in the cyberspace, it took me a couple of days to find it

**Comment by freddy38510** [comment]
Yeah i perfectly know that.
Probably i couldn't compile it because of too recent bison and texinfo version.

Edit: It took me all day but i did it. Running on archlinux 64 bits. Need texinfo 1.13a, gcc 3.9 and some tricks on spu.c

**Review by catara — COMMENTED** [review]
i could compile afterwards

**Pull request merged**
