### PR TITLE
Request mount immediately after pressing X in slaunch, processing stuff while slaunch closes.

### PR DESCRIPTION
**Pull request by DarjanKrijan**

### CODE REVIEW

**Comment by DarjanKrijan** [comment]
Hm, quick remark, hoping my change doesn't break this:

> Enable selection of emulator for PS1 and PS2 on B/C consoles (L2 = ps*_emu, R2 = ps*_netemu, R1 = toggle emulator during mount process)

Didn't know of this feature, is it meant for slaunch, WMM Games or both? Not sure if you need to press the shoulder buttons right as you press X.

**Comment by aldostools** [comment]
Yes, you should press the shoulder buttons right after you press X.

It should work for both (sLaunch / wMM) since the processing is done by wMM.
Unless the closing of slaunch takes too long and the polling of the L2/R2 is processed before the menu returns to XMB.

**Comment by DarjanKrijan** [comment]
I'm gonna test this

**Comment by DarjanKrijan** [comment]
Yes, something breaks here, the `ps1/2_(net)emu.self Enabled` message between `/path/to/game.iso` and `"game" loaded` doesn't even pop up anymore if mounted with slaunch, guessing some function errors out after not being able to grab the controller inputs?

Would there be workarounds? Like giving up controls before the `send_wm_request(path)`?

**Comment by aldostools** [comment]
The workaround would be to read the R2/L2 in slaunch.
Then add the parameter &emu=netemu if R2 is pressed or &emu=emu if L2 is pressed, before send the request.

I guess it is too much hasle only to save a few milliseconds. Anyway the mount takes various seconds and the user must wait.

**Comment by DarjanKrijan** [comment]
Actually, add exception for PS1/PS2 games is possible as it only affects them, for now at least.

I'll fix this.

**Comment by aldostools** [comment]
FYI 3a0b153a223735f9ca58f6c33056f6a29070cfa7 includes the exception that you suggested

**Comment by DarjanKrijan** [comment]
Something weirds out there, when I tried to add the exception similarly it crashed on XMB, now your change doesn't mount the PS1 game I'm trying with off slaunch :thinking:

**Comment by aldostools** [comment]
Oh I forgot to remove ! in (!ps1ps2)

**Comment by DarjanKrijan** [comment]
Looking good with the ! removed on 2nd.

**Comment by aldostools** [comment]
The installers are updated again with the fix aefcdff69778b12fd9dd3eab3b4408cfee3973e0

**Comment by DarjanKrijan** [comment]
Now I need to launch a lot of games/DVDs saving a good second each to make up for the time lost.

**Pull request merged**
