### PR TITLE
Use VMX SIMD instructions for drawing covers with multiple of 4 widths quicker

### PR DESCRIPTION
**Pull request by DarjanKrijan**
Improving performance of cover loading by moving pixels to the frame buffer with VMX SIMD instructions, theoretically doubling the throughput from using `uint64_t` to `vec_uint4` (16 bytes/128 bit SIMD).

Loading covers is still bottlenecked by slow jpg/png decoding, will come in soon with another commit that adds preliminary support for a custom uncompressed ARGB format for loading 2-3 large 272x384 covers per frame from SSD that will depend on this PR. Will make a video showing the huge difference in performance for convincing.

PS:
The wiki says covers **must** be a multiple of 4, but there are no checks for it in the PNG/JPG loaders.
It's would be better to add the `%4` checks there after loading header info and make the changes of the PR the default instead of using `uint64_t`.
Didn't know how the supplied PNG/JPG decoders are to be used exactly when exiting early, so didn't fiddle around with it for this commit.

### CODE REVIEW

**Comment by DarjanKrijan** [comment]
Small remark here.

This doesn't check if the destination (texture in frame buffer) is aligned to 16 bytes. Apparently the way Cell's VMX instructions work on unaligned addresses is instead of segfaulting (x86) it truncates the address to the next valid alignment (basically uses `address -= address%16`), so I've read somewhere recently.

If you experience any cover drawing artefacts in the future, like the selection not lining up with the cover, might be the culprit.

So far the cover widths of 272 pixels that I use render fine.

**Comment by aldostools** [comment]
In regards to this feature, in your PR you included png2argb.c in tools but not the binaries.
Could you include them? I had issue compiling this tool. Thanks.

BTW `address &= 0xfffffff0;` is faster than `address -= address%16` ;)

**Comment by DarjanKrijan** [comment]
Can compile for Windows with MinGW, guessing 32 bit is enough?

**Comment by aldostools** [comment]
yes. That will let other users test/use your new feature.

**Pull request merged**
