### PR TITLE
Fix folder mapping not working for anything but ROMS

### PR DESCRIPTION
**Pull request by Dvvarf**
Very simple fix for #374.

As proposed, scan function now looks at path "as as" first and only after that starts looking for delimiter.

### CODE REVIEW

**Comment by aldostools** [comment]
Sorry but I don't understand your issue. The folder mapping is working fine.

Here is an example:
image

As you can see in the screenshot, I redirected GAMES in PS3ISO.INI, so the files in /GAMES will show in /PS3ISO

I have a test game duplicated in both folders, but the one says [STORED IN GAMES]

In this screenshot I mounted **/PS3ISO**/Angry Birds [STORED IN GAMES].iso which is physically located in /GAMES
image

**Comment by Dvvarf** [comment]
Maybe I don't understand the directory structure you're using... What I expected:

1. Put PS3ISO.INI in directory DIR1. PS3ISO.INI contains one string "path/to/iso/directory".
2. Launch ps3netsrv pointing to DIR1.
3. Expect ps3netsrv to serve PS3ISO from "path/to/iso/directory".

This is what I get (just an example with PSPISO, for other I get the same result):
webman-mod-mapping

ps3netsrv command line is:
`ps3netsrv.exe "D:\Soft\ps3\mapping test\" 38008`

"D:\Soft\ps3\mapping test\" looks like this:
webman-mod-mapping

"_ROMS_/GBA" does indeed contain single ROM, which is Advance Wars.gba.

PS3ISO.INI and PSXISO.INI contain network paths, which do not work also, but that's OK, I think.

**Comment by aldostools** [comment]
+I think you're doing the mapping in the wrong way.

This is the structure that I used:
1- My shared folder is C:\DATA\SHARE
2- It contains various sub folders: GAMES, PS3ISO, PSPISO, PSXISO, DVDISO, ROMS, etc.
Example: C:\DATA\SHARE\PS3ISO contains 1 file: Angry Birds [BLUS31273].iso (see the picture below)
3- ps3netsrv is in C:\DATA\SHARE\ps3netsrv.exe
4- PS3ISO.INI is next to the folders listed in number 2,  i.e.  C:\DATA\SHARE\PS3ISO.INI
5- PS3ISO.INI is adding the content of X:\Soft\ps3\mapping test\_PS3ISO_ to C:\DATA\SHARE\PS3ISO (see picture)
6- As ps3netsrv is in the same folder of PS3ISO, I simply run it without parameters: C:\DATA\SHARE\ps3netsrv.exe

image

**** EDIT ****
VERY IMPORTANT: The sub folders in the SHARE folder must be named like number 2, NOT like you did: `_PSPISO_`

The paths listed inside PS3ISO.INI, PSPISO.INI, etc. can have any name.

**Comment by Dvvarf** [comment]
Yes, if used like you described, the mapping works.

However, don't you think it would be better to eliminate the need to keep empty directories if user doesn't use them?

For my case I'd have this directory to use with ps3netsrv:
```
PS3ISO (empty)
PSPISO (empty)
PSXISO (empty)
ROMS (empty)
PS3ISO.INI
PSPISO.INI
PSXISO.INI
ROMS.INI
```
instead of just this:
```
PS3ISO.INI
PSPISO.INI
PSXISO.INI
ROMS.INI
```

Proposed solution (and pull request) does not break the first case, but allows to use the second one. Makes it a quality of life improvement, not a fix, I guess.

**Comment by aldostools** [comment]
The folders cannot be eliminated easily in the source code, because the INI acts as an extension of the folder. If the folder doesn't exist, the INI file is not processed.

The folders GAMES, PS3ISO, PSPISO, etc. are required and it's optional that you put files inside or not.
That's how the tool originally was designed. I only extended the function to also read files from other folders.

**Comment by Dvvarf** [comment]
That's not true, it does.

ps3netsrv know nothing about these directories.

> If the folder doesn't exist, the INI file is not processed.

That's exactly what this pull request changes.

**Comment by aldostools** [comment]
Ok I will review and test your changes. If it doesn't conflict with the current functionality, I will commit it.
I first needed to understand your issue, because the mapping was working properly.

**Comment by Dvvarf** [comment]
Oh, I see. Thank you!

The change is really small (7 modified lines, in fact), I hope it doesn't break anything. Personally, I've been running the modified version for a month now and did not encounter any problems...

**Comment by aldostools** [comment]
I reviewed the 7 lines and seems to be safe to commit, although I'm not sure that it would work without the empty folders as you said.

**Pull request merged**
