### PR TITLE
ps3netsrv - Refactor

### PR DESCRIPTION
**Pull request by kam821**
- Removed C-style casts
- Replace some dynamic allocated variables by Smart Pointers
- Replaced some expanded if conditions by ternary operators (hope this will help the compiler to avoid conditional jumps)
- Changed some char assignment from 0 to '\0'
- Make comments/code structure more consistent

This is beginning of, at least for now, pure draft/concept.
I do not make any guarantees that everything is working for now.

Imo, there are many segments in the webMAN-MOD that need attention.
It would be great if at least most dynamic allocation based on raw pointers would be removed (they cause only problems, mostly).
What do you think @aldostools ?
Regards.

### CODE REVIEW

**Comment by kam821** [comment]
@aldostools 
btw, I asked about this piece of code once:
```
if (this_r < 0)
{
	fprintf(stderr, "VISO: read_file failed on %s\n", fileList->path);
	return r;
}

if (this_r != (int64_t)to_read)
{
	fprintf(stderr, "VISO: read on file %s returned less data than expected (file modified?)\n", fileList->path);
	return r;
}
```

I changed to_read casting (uint64_t -> int64_t) to this_r casting (int64_t -> uint64_t), but...
You wrote that converting from unsigned to signed is recommended.
However, in this case, there is a detection that this_r is not a negative number and uint64_t has higher numeric limit than int64_t, so imo, the problem may occur in uint64_t -> int64_t, as it is now.

**Review by aldostools — APPROVED** [review]
I will approve the PR, but I need feedback about how it behaves compiling on different platforms.

**Comment by kam821** [comment]
Could you try compile this in a win32 environment?
I made some changes in win32 specific parts/files, which I'm not able to test on win32 right now.

**Comment by aldostools** [comment]
> Could you try compile this in a win32 environment?
> I made some changes in win32 specific parts/files, which I'm not able to test on win32 right now.

This pull request is still a work in progress: Draft pull requests cannot be merged. Therefore I cannot compile it.

**Comment by kam821** [comment]
@aldostools 
I pushed another commit, because I found some bugs.
Now compilation is successful, at least on Windows and Linux.
However, I have questions:
1) Static analysis found two implicit strcmp comparision and I'm not sure, how it should looks like.
Could you take a look at it? (src/main.cpp, line: 2006, 2039 in latest commit in this PR).
2) Do you think replacing winsock.h by winsock2.h is a good idea?
I had to do this because the SD_BOTH macro doesn't exist in the winsock.h header (and this header itself is incredibly outdated)

**Comment by aldostools** [comment]
1. The strcmp comparisons in lines 2006 and 2039 are not important. They show only the new IP addresses for display information.
They look ok as they are now.

2. I don't see why you need the SD_BOTH macro. The project has been working fine with winsock.h

Your changes do not compile on Windows 10 using Estwald's PSL1GHT SDK environment:
```
g++  -Wall -Wno-format -I./include -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DPOLARSSL -D_OS_WINDOWS -static -O3 -s -DNDEBUG  -c -o src/main.o src/main.cpp
In file included from c:\psdk3v2\mingw\bin\../lib/gcc/mingw32/4.5.2/include/c++/cstdint:35:0,
                 from src/main.cpp:2:
c:\psdk3v2\mingw\bin\../lib/gcc/mingw32/4.5.2/include/c++/bits/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
src/main.cpp: In function 'int64_t calculate_directory_size(char*)':
src/main.cpp:415:2: error: 'unique_ptr' is not a member of 'std'
src/main.cpp:415:18: error: expected primary-expression before 'char'
src/main.cpp:415:18: error: expected ';' before 'char'
src/main.cpp:416:21: error: 'newpath' was not declared in this scope
make: *** [src/main.o] Error 1

**Comment by aldostools** [comment]
EDIT: Fixed `makefile` to be able to compile the project on Windows 10

**Comment by kam821** [comment]
@aldostools 
Ah, differences in the environment are as usual :)
I was able to compile the program on Windows 10 without any problems even before the missing std flag was added.
The SD_BOTH macro is used in the compat.h file:
```
#ifndef SHUT_RD
#define SHUT_RD SD_RECEIVE
#endif

#ifndef SHUT_WR
#define SHUT_WR SD_SEND
#endif

#ifndef SHUT_RDWR
#define SHUT_RDWR SD_BOTH
#endif
```
and it is defined in winsock2.h as:
```
Declared In: winsock2.h

Definition:  
#define SD_BOTH 0x02

Replacement:  
```

**Pull request merged**
